### ISSUE TITLE
Faulty error message handling

### ISSUE THREAD

**Issue by JohannesGarm** [clicon/clixon-pyapi#25]
From clixon.py:

` 
except Exception as e:
            logger.error(f"Got exception from Clixon.__exit__: {e}")
            raise Exception(f"{e}")
`

Logs:

`Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: pyserver[2171342] clixon.py:136: Got exception from Clixon.__exit__: 'str' object has no attribute 'keys'
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: pyserver[2171342] client.py:84: Catched an module exception
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: Traceback (most recent call last):
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/clixon.py", line 129, in __exit__
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     send(self.__socket, config, pp)
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/sock.py", line 106, in send
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     data = data.dumps()
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/element.py", line 342, in dumps
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     xmlstr += child.dumps()
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/element.py", line 342, in dumps
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     xmlstr += child.dumps()
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/element.py", line 342, in dumps
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     xmlstr += child.dumps()
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   [Previous line repeated 6 more times]
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/element.py", line 332, in dumps
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     attr_string = child.get_attributes_str()
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/element.py", line 285, in get_attributes_str
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     for key in self.attributes.keys():
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: AttributeError: 'str' object has no attribute 'keys'
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: During handling of the above exception, another exception occurred:
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: Traceback (most recent call last):
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/client.py", line 79, in services_commit_cb
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     run_modules(modules, service_name, instance)
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/modules.py", line 39, in run_modules
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     with Clixon(sockpath=sockpath) as cd:
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:   File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/clixon.py", line 137, in __exit__
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]:     raise Exception(f"{e}")
Apr 04 07:34:46 nsolab-02 clixon_server.py[2171342]: Exception: 'str' object has no attribute 'keys'`

**Comment by JohannesGarm** [comment]
I misunderstood the message - there was no error in the error handling itself.
